matrix:
  include:
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on 
script:
  - dir
  - dir > report.json
  - git branch
  - git config --global user.email "skarri@outlook.com"
  - git config --global user.name "skarri-microsoft"
  - git checkout -b azure-cosmosdb-mongo-tests
  - git status
  - git add report.json
  - git status
  - git commit -m "update report json"
  - git status
  - git remote add azure-cosmosdb-mongo-tests https://74dde593efa70e5773420f1e493887f191ca397c@github.com/skarri-microsoft/azure-cosmosdb-mongo-tests.git
  - git push --set-upstream origin azure-cosmosdb-mongo-tests