matrix:
  include:
    - name: "Python 3.8.2 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on 
script:
  - dir
  - dir > report1.json
  - git branch
  - git config --global user.email "skarri@outlook.com"
  - git config --global user.name "skarri-microsoft"
  - curl -u "skarri-microsoft:752e7cda672c5ebee56fa74853c53c5381289221" https://github.com/skarri-microsoft/azure-cosmosdb-mongo-tests.git
  - git remote set-url origin https://752e7cda672c5ebee56fa74853c53c5381289221@github.com/skarri-microsoft/azure-cosmosdb-mongo-tests.git
  - git checkout temp
  - git branch
  - git status
  - git add report1.json
  - git status
  - git commit -m "update report json"
  - git status
  - cat report1.json
  - git push -fq origin temp